SELECT YEAR(a.SALES_DATE) as YEAR, MONTH(a.SALES_DATE) as MONTH, COUNT(DISTINCT a.USER_ID) as PUCHASED_USERS, ROUND(COUNT(DISTINCT a.USER_ID)/c.cnt, 1) as PUCHASED_RATIO
FROM ONLINE_SALE a
LEFT JOIN(SELECT * FROM USER_INFO) b on b.USER_ID = a.USER_ID
LEFT JOIN(SELECT COUNT(*) as cnt FROM USER_INFO WHERE JOINED BETWEEN "2021-01-01" AND "2021-12-31") c on 1 = 1
WHERE b.JOINED BETWEEN "2021-01-01" AND "2021-12-31"
GROUP BY YEAR,MONTH
ORDER BY YEAR, MONTH