SELECT a.CAR_ID,
CASE
WHEN SUM(b.avail) = 1 THEN '대여중'
ELSE '대여 가능'
end
AS AVAILABILITY
from CAR_RENTAL_COMPANY_RENTAL_HISTORY a 
LEFT JOIN(SELECT *,
CASE 
WHEN '2022-10-16' BETWEEN start_date AND end_date THEN '1'
ELSE '0'
END
AS avail
from CAR_RENTAL_COMPANY_RENTAL_HISTORY) b on b.HISTORY_ID = a.HISTORY_ID
GROUP BY CAR_ID
ORDER BY CAR_ID desc;