SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, b.FAVORITES
from REST_INFO a
LEFT JOIN(SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) b on b.FOOD_TYPE = a.FOOD_TYPE
WHERE a.FAVORITES = b.FAVORITES
ORDER BY FOOD_TYPE DESC;